openapi: 3.0.1

info:
  title: ms-banking-products-api
  description: API for ms-banking-products
  version: 1.0.0
servers:
  - url: https://localhost:8091
tags:
  - name: ms-banking-products-api
    description: API for ms-banking-products
paths:
  /products:
    get:
      summary: Retrieve all products
      operationId: retrieveAllProducts
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Products'
    post:
      summary: Save new product
      operationId: saveProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDTO"
    put:
      summary: Update an existing product
      operationId: updateProduct
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDTO"
  /products/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: product ID
        schema:
          type: integer
          format: int64
          minimum: 1
    get:
      summary: Retrieve a product
      operationId: retrieveProduct
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDTO"
    delete:
      summary: Delete a product
      operationId: deleteProduct
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductDTO"
components:
  schemas:
    Products:
      type: array
      items:
        $ref: "#/components/schemas/ProductDTO"
    ProductDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        productType:
          type: string
        name:
          type: string
        productCategory:
          type: string
        state:
          type: string
        createdAt:
          type: string
      required:
        - id
        - productType
        - productCategory